language: objective-c
osx_image: xcode10.2

install:
  - gem install xcpretty --no-document --quiet

script:
  - set -o pipefail
# build sample app for simulator (also builds framework)
  - xcodebuild -project ISHPullUpSample/ISHPullUpSample.xcodeproj -scheme ISHPullUpSample -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.2' clean build | xcpretty
